name: gentle_server
description: Lightweight and convenient server infrastructure written in Dart.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  meta: ^1.8.0
  json_annotation: ^4.6.0
  gentle_lints:
    git:
      url: git@github.com:GentleTechTeam/GentleLints.git

dev_dependencies:
  json_serializable: ^6.1.6
  build_runner: ^2.1.10
